version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: wind_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/wind_auth?schema=public
      JWT_SECRET: your-super-secret-key
      JWT_ACCESS_EXPIRY: 15m
      JWT_REFRESH_EXPIRY: 7d
      PORT: 4000
      CORS_ORIGINS: http://localhost:3000
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 100
      SUPER_ADMIN_EMAIL: superadmin@example.com
      SUPER_ADMIN_PASSWORD: superadminpassword
    depends_on:
      - db
    # Optional: for development with hot-reloading
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # command: npm run dev

volumes:
  db_data:
