export { default as authRoutes } from './auth.routes';
export { default as rolesRoutes } from './roles.routes';
export { default as permissionsRoutes } from './permissions.routes';
export { default as oidcRoutes } from './oidc.routes';
export { default as usersRoutes, userSpecificRouter } from './users.routes';
export { default as configRoutes } from './config.routes';
export { default as resourcesRoutes } from './resources.routes';
export { default as userDetailsRoutes } from './userDetails.routes';
export { default as adminRoutes } from './admin.routes';
export { default as passwordResetRoutes } from './passwordReset.routes';
export { default as internalRoutes } from './internal.routes';
